FROM ubuntu:20.04

WORKDIR /home/

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y git \
	python3.7 \
	wget \
	openjdk-11-jdk

## get apache maven
RUN wget https://aws-glue-etl-artifacts.s3.amazonaws.com/glue-common/apache-maven-3.6.0-bin.tar.gz
RUN tar -xvf apache-maven-3.6.0-bin.tar.gz

## get aws spark distro
RUN wget https://aws-glue-etl-artifacts.s3.amazonaws.com/glue-3.0/spark-3.1.1-amzn-0-bin-3.2.1-amzn-3.tgz
RUN tar -xvf spark-3.1.1-amzn-0-bin-3.2.1-amzn-3.tgz
ENV SPARK_HOME=/home/spark-2.4.3-bin-spark-3.1.1-amzn-0-bin-3.2.1-amzn-3

## get aws glue libs main branch
RUN wget https://github.com/awslabs/aws-glue-libs/archive/refs/tags/v3.0.tar.gz --no-check-certificate
RUN tar -xvf v3.0.tar.gz